project_name: slack

builds:
  - main: ./cmd/gh-slack
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    ldflags:
      - -X github.com/rneatherway/gh-slack/internal/version.version={{.Version}}
      - -X github.com/rneatherway/gh-slack/internal/version.commit={{.Commit}}

archives:
  - format: binary
    name_template: "slack-{{.Os}}-{{.Arch}}"

