project_name: slack

builds:
  - main: ./cmd/slack-to-md
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -X github.com/rneatherway/slack-to-md/internal/version.version={{.Version}}
      - -X github.com/rneatherway/slack-to-md/internal/version.commit={{.Commit}}

archives:
  - format: binary
    name_template: "slack-{{.Os}}-{{.Arch}}"

